"use strict";
var Handler_1 = require("./structures/Handler");
var VorteClient_1 = require("./structures/VorteClient");
var dotenv_1 = require("dotenv");
dotenv_1.config({ path: __dirname + "/../.env" });
var bot = new VorteClient_1.VorteClient();
var handler = new Handler_1.Handler(bot);
handler.loadCommands();
handler.loadEvents();
bot.login(process.env.TOKEN);
module.exports = handler;
